{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Sol","night_text":"Céu limpo"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Parcialmente nublado","night_text":"Parcialmente nublado"}
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Nublado","night_text":"Nublado"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Encoberto","night_text":"Encoberto"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Neblina","night_text":"Neblina"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Possibilidade de chuva irregular","night_text":"Possibilidade de chuva irregular"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Possibilidade de neve irregular","night_text":"Possibilidade de neve irregular"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Possibilidade de neve molhada irregular","night_text":"Possibilidade de neve molhada irregular"}
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Possibilidade de chuvisco gelado irregular","night_text":"Possibilidade de chuvisco gelado irregular"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Possibilidade de trovoada","night_text":"Possibilidade de trovoada"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Rajadas de vento com neve","night_text":"Rajadas de vento com neve"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Nevasca","night_text":"Nevasca"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Nevoeiro","night_text":"Nevoeiro"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Nevoeiro gelado","night_text":"Nevoeiro gelado"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuvisco irregular","night_text":"Chuvisco irregular"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuvisco","night_text":"Chuvisco"}
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuvisco gelado","night_text":"Chuvisco gelado"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuvisco forte gelado","night_text":"Chuvisco forte gelado"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuva fraca irregular","night_text":"Chuva fraca irregular"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuva fraca","night_text":"Chuva fraca"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Períodos de chuva moderada","night_text":"Períodos de chuva moderada"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuva moderada","night_text":"Chuva moderada"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Períodos de chuva forte","night_text":"Períodos de chuva forte"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuva forte","night_text":"Chuva forte"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuva fraca e gelada","night_text":"Chuva fraca e gelada"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuva gelada moderada ou forte","night_text":"Chuva gelada moderada ou forte"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuva fraca com neve","night_text":"Chuva fraca com neve"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuva forte ou moderada com neve","night_text":"Chuva forte ou moderada com neve"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Queda de neve irregular e fraca","night_text":"Queda de neve irregular e fraca"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Queda de neve fraca","night_text":"Queda de neve fraca"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Queda de neve moderada e irregular","night_text":"Queda de neve moderada e irregular"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Queda de neve moderada","night_text":"Queda de neve moderada"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Queda de neve forte e irregular","night_text":"Queda de neve forte e irregular"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Neve intensa","night_text":"Neve intensa"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Granizo","night_text":"Granizo"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Aguaceiros fracos","night_text":"Aguaceiros fracos"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Aguaceiros moderados ou fortes","night_text":"Aguaceiros moderados ou fortes"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuva torrencial","night_text":"Chuva torrencial"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Aguaceiros fracos com neve","night_text":"Aguaceiros fracos com neve"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Aguaceiros moderados ou fortes com neve","night_text":"Aguaceiros moderados ou fortes com neve"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuva fraca com neve","night_text":"Chuva fraca com neve"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuva moderada ou forte com neve","night_text":"Chuva moderada ou forte com neve"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Aguaceiros fracos com granizo","night_text":"Aguaceiros fracos com granizo"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Aguaceiros moderados ou fortes com granizo","night_text":"Aguaceiros moderados ou fortes com granizo"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuva fraca irregular com trovoada","night_text":"Chuva fraca irregular com trovoada"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Chuva moderada ou forte com trovoada","night_text":"Chuva moderada ou forte com trovoada"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Neve fraca irregular com trovoada","night_text":"Neve fraca irregular com trovoada"},
{"lang_name":"Portuguese","lang_iso":"pt","day_text":"Neve moderada ou forte com trovoada","night_text":"Neve moderada ou forte com trovoada"},